//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quant_BackTest_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backtest
    {
        public int backtest_id { get; set; }
        public Nullable<int> strategy_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> data_id { get; set; }
        public Nullable<float> sy { get; set; }
        public Nullable<float> nsy { get; set; }
        public Nullable<float> hc { get; set; }
        public Nullable<float> xp { get; set; }
        public Nullable<float> sx { get; set; }
        public string report_path { get; set; }
    
        public virtual strategy strategy { get; set; }
    }
}
