//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quant_BackTest_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public data()
        {
            this.backtest = new HashSet<backtest>();
        }
    
        public int data_id { get; set; }
        public string data_path { get; set; }
        public int data_type { get; set; }
        public string user_id { get; set; }
        public string data_name { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<backtest> backtest { get; set; }
        public virtual user user { get; set; }
    }
}
