//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quant_BackTest_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int data_id { get; set; }
        public string data_path { get; set; }
        public Nullable<int> data_type { get; set; }
        public string user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
